/**
 * Built-in fallback SAP payload template.
 *
 * Mirrors the canonical `sap_payload_templates` row used by Lovable Cloud and
 * `vms.siplproducts.com`. It is consumed when a self-hosted deployment has
 * NOT seeded the `sap_payload_templates` table, so SAP Sync still works
 * dynamically (all `{{vendor.*}}` / `{{override.*}}` placeholders are resolved
 * against the live vendor row + confirmation-dialog overrides + tenant
 * defaults). No hardcoded vendor data, endpoints, or credentials.
 */
export const DEFAULT_SAP_PAYLOAD_TEMPLATE: any = {
  cdi: "{{override.cdi|default:X}}",
  city: "{{vendor.registered_city|trunc:40}}",
  msme: "{{override.msme|msme_flag}}",
  akont: "{{override.akont|default:155000005}}",
  bukrs: "{{override.bukrs|default:1000}}",
  bzirk: "",
  fdgrv: "{{override.fdgrv|default:A1}}",
  idnum: "{{vendor.reference_no}}",
  inco1: "",
  inco2: "",
  kalks: "",
  kalsk: "{{override.kalsk|default:L1}}",
  kdgrp: "",
  kkber: "",
  konda: "",
  ktgrd: "",
  kurst: "",
  kzazu: "",
  langu: "EN",
  lebre: "{{override.lebre|default:X}}",
  lprio: "",
  name1: "{{vendor.legal_name|trunc:40}}",
  name2: "{{vendor.relative_name|trunc:40}}",
  name3: "",
  pernr: "",
  pltyp: "",
  qland: "",
  qsrec: "",
  spart: "",
  title: "{{override.title|default:0003}}",
  uebto: "",
  untto: "",
  versg: "",
  vkbur: "",
  vkgrp: "",
  vkorg: "{{override.vkorg|default:1000}}",
  vsbed: "",
  vtweg: "",
  waers: "{{override.waers|default:INR}}",
  webre: "{{override.webre|default:X}}",
  witht: "",
  xzver: "",
  zterm: "",
  zuawa: "{{override.zuawa|default:014}}",
  UPLOAD: "{{uploads}}",
  idnum2: "{{override.idnum2|msme_idnum}}",
  idtype: "SOLMN1",
  region: "{{region(vendor.registered_state)}}",
  sterm1: "{{vendor.legal_name|trunc:20}}",
  sterm2: "{{vendor.trade_name_first_word|trunc:20}}",
  street: "{{vendor.registered_address|trunc:60}}",
  zinco1: "",
  zinco2: "",
  zvkorg: "",
  zwaers: "",
  zzterm: "",
  bp_type: "",
  country: "IN",
  idtype2: "ZMSMEN",
  taxkd01: "",
  taxkd02: "",
  taxkd03: "",
  taxkd04: "",
  taxkd05: "",
  taxkd06: "",
  taxkd07: "",
  taxtype: "{{override.taxtype|default:IN3}}",
  vendors: [
    {
      cdi: "{{override.cdi|default:X}}",
      city: "{{vendor.registered_city|trunc:40}}",
      msme: "{{override.msme|msme_flag}}",
      akont: "{{override.akont|default:155000005}}",
      bukrs: "{{override.bukrs|default:1000}}",
      idnum: "",
      inco1: "",
      inco2: "",
      kalsk: "{{override.kalsk|default:L1}}",
      ktokk: "",
      langu: "EN",
      lifnr: "",
      name2: "{{vendor.relative_name|trunc:40}}",
      name3: "",
      nodel: "",
      pernr: "",
      qland: "",
      qsrec: "",
      vkorg: "{{override.vkorg|default:1000}}",
      waers: "{{override.waers|default:INR}}",
      webre: "{{override.webre|default:X}}",
      witht: "",
      zterm: "",
      zuawa: "{{override.zuawa|default:014}}",
      idtype: "",
      region: "{{region(vendor.registered_state)}}",
      sterm1: "{{vendor.legal_name|trunc:20}}",
      sterm2: "",
      street: "{{vendor.registered_address|trunc:60}}",
      bp_type: "",
      country: "IN",
      taxtype: "{{override.taxtype|default:IN3}}",
      district: "",
      due_digi: "",
      house_no: "",
      location: "",
      taxnumxl: "{{vendor.gstin|trunc:20}}",
      j_1ipanno: "{{vendor.pan|trunc:10}}",
      partn_cat: "{{override.partn_cat|default:2}}",
      pur_block: "",
      smtp_addr: "{{vendor.primary_email_or_fallback|trunc:241}}",
      ven_class: "{{override.ven_class}}",
      wt_subjct: "",
      wt_withcd: "",
      block_func: "",
      comp_block: "",
      mob_number: "{{vendor.primary_phone_or_fallback|trunc:30}}",
      postl_cod1: "{{vendor.registered_pincode|trunc:10}}",
      str_suppl1: "{{vendor.registered_address_line2|trunc:40}}",
      str_suppl2: "{{vendor.registered_address_line3|trunc:40}}",
      str_suppl3: "{{vendor.registered_address_line4|trunc:40}}",
      tel_number: "{{vendor.registered_phone|trunc:30}}",
      cent_pur_block: "",
      cent_post_block: "",
    },
  ],
  CLASSIFY: {
    CAT_VENDOR: [{ CATV: "{{classify.CATV|upper}}" }],
    MAT_GRP_VENDOR: [{ MGV: "{{classify.MGV|upper}}" }],
    LOCATION_VENDOR: [{ LOCV: "{{classify.LOCV|upper}}" }],
    IDENTIFICATION_SOURCE: [{ IDS: "{{classify.IDS|upper}}" }],
  },
  bank_key: "{{vendor.ifsc_code|trunc:15}}",
  bpartner: "",
  ctrl_key: "",
  district: "",
  due_digi: "",
  house_no: "",
  j_1iexcd: "",
  j_1iexco: "",
  j_1iexdi: "",
  j_1iexrg: "",
  j_1iexrn: "",
  j_1isern: "",
  legaenty: "",
  legaform: "",
  location: "",
  taxnumxl: "{{vendor.gstin|trunc:20}}",
  bank_acct: "{{vendor.account_number|trunc:18}}",
  bank_ctry: "IN",
  customers: [
    {
      bukrs: "",
      idnum: "",
      kunnr: "",
      zterm: "",
      idtype: "",
      identrydate: "",
      idinstitute: "",
    },
  ],
  j_1icstno: "",
  j_1ilstno: "",
  j_1ipanno: "{{vendor.pan|trunc:10}}",
  partn_cat: "{{override.partn_cat|default:2}}",
  partn_grp: "{{override.partn_grp|default:ZDOM}}",
  smtp_addr: "{{vendor.primary_email|trunc:241}}",
  ven_class: "{{override.ven_class}}",
  wt_subjct: "",
  wt_withcd: "",
  j_1iexcicu: "",
  mob_number: "{{vendor.primary_phone|trunc:30}}",
  postl_cod1: "{{vendor.registered_pincode|trunc:10}}",
  str_suppl1: "{{vendor.registered_address_line2|trunc:40}}",
  str_suppl2: "{{vendor.registered_address_line3|trunc:40}}",
  str_suppl3: "{{vendor.registered_address_line4|trunc:40}}",
  tel_number: "{{vendor.registered_phone|trunc:30}}",
  bankdetailid: "0001",
  accountholder: "{{vendor.account_holder_name|trunc:60}}",
  bankaccountname: "{{vendor.account_holder_name|trunc:60}}",
};
