#!/usr/bin/env bash
# 20-supabase: clone stack, generate secrets, write .env, start containers
set -Eeuo pipefail

log "Preparing Supabase stack at $BACKEND_DIR"

if [[ -f "$BACKEND_DIR/docker-compose.yml" ]]; then
  echo "Existing docker-compose.yml found — skipping clone."
else
  echo "Cloning supabase/supabase (shallow)..."
  rm -rf /tmp/supabase-src
  git clone --depth 1 https://github.com/supabase/supabase /tmp/supabase-src
  rsync -a /tmp/supabase-src/docker/ "$BACKEND_DIR/"
  rm -rf /tmp/supabase-src
  echo "Stack files copied."
fi

cd "$BACKEND_DIR"
[[ -f .env.example ]] || { echo ".env.example missing in $BACKEND_DIR"; exit 1; }
mkdir -p volumes/db/data volumes/storage volumes/functions volumes/logs

SECRETS_FILE="$BACKEND_DIR/.env.secrets"

mint_jwt() {
  local role="$1" secret="$2"
  python3 - "$role" "$secret" <<'PY'
import sys, hmac, hashlib, base64, json, time
role, secret = sys.argv[1], sys.argv[2]
def b64url(b): return base64.urlsafe_b64encode(b).rstrip(b'=').decode()
header  = b64url(json.dumps({"alg":"HS256","typ":"JWT"}, separators=(",",":")).encode())
now = int(time.time())
payload = b64url(json.dumps({
  "role": role, "iss": "supabase", "iat": now, "exp": now + 60*60*24*365*10,
}, separators=(",",":")).encode())
signing_input = f"{header}.{payload}".encode()
sig = b64url(hmac.new(secret.encode(), signing_input, hashlib.sha256).digest())
print(f"{header}.{payload}.{sig}")
PY
}
rand_hex() { openssl rand -hex "${1:-32}"; }
rand_b64() { openssl rand -base64 "${1:-32}" | tr -d '\n=+/' | cut -c1-"${2:-32}"; }

if [[ $RESET_SECRETS -eq 1 && -f "$SECRETS_FILE" ]]; then
  echo "Resetting secrets (backup: ${SECRETS_FILE}.bak.$(date +%s))"
  mv "$SECRETS_FILE" "${SECRETS_FILE}.bak.$(date +%s)"
fi

if [[ -f "$SECRETS_FILE" ]]; then
  log "Reusing existing $SECRETS_FILE"
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
else
  log "Generating fresh secrets -> $SECRETS_FILE"
  POSTGRES_PASSWORD="$(rand_b64 48 32)"
  JWT_SECRET="$(rand_hex 32)"
  DASHBOARD_USERNAME="supabase"
  DASHBOARD_PASSWORD="$(rand_b64 48 24)"
  SECRET_KEY_BASE="$(rand_hex 32)"
  VAULT_ENC_KEY="$(rand_b64 48 32)"
  LOGFLARE_PUBLIC_ACCESS_TOKEN="$(rand_hex 32)"
  LOGFLARE_PRIVATE_ACCESS_TOKEN="$(rand_hex 32)"
  POOLER_TENANT_ID="${POOLER_TENANT_ID:-1000}"
  ANON_KEY="$(mint_jwt anon "$JWT_SECRET")"
  SERVICE_ROLE_KEY="$(mint_jwt service_role "$JWT_SECRET")"

  umask 077
  cat > "$SECRETS_FILE" <<EOF
# Generated by deploy-vms-server.sh on $(date -Iseconds)
POSTGRES_PASSWORD='$POSTGRES_PASSWORD'
JWT_SECRET='$JWT_SECRET'
ANON_KEY='$ANON_KEY'
SERVICE_ROLE_KEY='$SERVICE_ROLE_KEY'
DASHBOARD_USERNAME='$DASHBOARD_USERNAME'
DASHBOARD_PASSWORD='$DASHBOARD_PASSWORD'
SECRET_KEY_BASE='$SECRET_KEY_BASE'
VAULT_ENC_KEY='$VAULT_ENC_KEY'
LOGFLARE_PUBLIC_ACCESS_TOKEN='$LOGFLARE_PUBLIC_ACCESS_TOKEN'
LOGFLARE_PRIVATE_ACCESS_TOKEN='$LOGFLARE_PRIVATE_ACCESS_TOKEN'
POOLER_TENANT_ID='$POOLER_TENANT_ID'
EOF
  chmod 600 "$SECRETS_FILE"
fi
export ANON_KEY SERVICE_ROLE_KEY DASHBOARD_USERNAME DASHBOARD_PASSWORD

log "Writing $BACKEND_DIR/.env"
ENV_FILE="$BACKEND_DIR/.env"
cp -f "$BACKEND_DIR/.env.example" "$ENV_FILE"

set_env() {
  local key="$1" val="$2" esc
  esc=$(printf '%s' "$val" | sed -e 's/[\/&]/\\&/g')
  if grep -qE "^${key}=" "$ENV_FILE"; then
    sed -i -E "s|^${key}=.*|${key}=${esc}|" "$ENV_FILE"
  else
    echo "${key}=${val}" >> "$ENV_FILE"
  fi
}

set_env POSTGRES_PASSWORD             "$POSTGRES_PASSWORD"
set_env JWT_SECRET                    "$JWT_SECRET"
set_env ANON_KEY                      "$ANON_KEY"
set_env SERVICE_ROLE_KEY              "$SERVICE_ROLE_KEY"
set_env DASHBOARD_USERNAME            "$DASHBOARD_USERNAME"
set_env DASHBOARD_PASSWORD            "$DASHBOARD_PASSWORD"
set_env SECRET_KEY_BASE               "$SECRET_KEY_BASE"
set_env VAULT_ENC_KEY                 "$VAULT_ENC_KEY"
set_env LOGFLARE_PUBLIC_ACCESS_TOKEN  "$LOGFLARE_PUBLIC_ACCESS_TOKEN"
set_env LOGFLARE_PRIVATE_ACCESS_TOKEN "$LOGFLARE_PRIVATE_ACCESS_TOKEN"
set_env POOLER_TENANT_ID              "$POOLER_TENANT_ID"

set_env SITE_URL                      "$PUBLIC_BASE_URL"
set_env API_EXTERNAL_URL              "${PUBLIC_BASE_URL}/supabase"
set_env SUPABASE_PUBLIC_URL           "${PUBLIC_BASE_URL}/supabase"
set_env ADDITIONAL_REDIRECT_URLS      ""

set_env STUDIO_DEFAULT_ORGANIZATION   "Sharvi"
set_env STUDIO_DEFAULT_PROJECT        "VMS-DEV"

set_env KONG_HTTP_PORT                "$KONG_HTTP_PORT"
set_env KONG_HTTPS_PORT               "$KONG_HTTPS_PORT"
set_env STUDIO_PORT                   "$STUDIO_PORT"
set_env POSTGRES_PORT                 "$POSTGRES_PORT"

set_env ENABLE_EMAIL_SIGNUP           "true"
set_env ENABLE_EMAIL_AUTOCONFIRM      "false"
set_env ENABLE_PHONE_SIGNUP           "false"
set_env ENABLE_PHONE_AUTOCONFIRM      "false"
set_env DISABLE_SIGNUP                "false"

chmod 600 "$ENV_FILE"

# Bind Kong/Studio/Postgres to localhost ONLY (override compose port mapping)
log "Writing docker-compose.override.yml (localhost-only port binding)"
cat > "$BACKEND_DIR/docker-compose.override.yml" <<EOF
# Auto-generated by deploy-vms-server.sh
# Forces all exposed ports to 127.0.0.1 so only Nginx is public.
services:
  kong:
    ports:
      - "127.0.0.1:${KONG_HTTP_PORT}:8000/tcp"
      - "127.0.0.1:${KONG_HTTPS_PORT}:8443/tcp"
  studio:
    ports:
      - "127.0.0.1:${STUDIO_PORT}:3000/tcp"
  db:
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432/tcp"
EOF

log "Pulling images"
( cd "$BACKEND_DIR" && docker compose pull )

log "Starting Supabase stack"
( cd "$BACKEND_DIR" && docker compose up -d )

log "Waiting for Kong on 127.0.0.1:${KONG_HTTP_PORT} (up to 180s)"
ready=0
for i in $(seq 1 90); do
  if curl -sSf -o /dev/null "http://127.0.0.1:${KONG_HTTP_PORT}/"; then
    ready=1
    echo "Kong is up after ${i}x2s."
    break
  fi
  sleep 2
done
[[ $ready -eq 1 ]] || echo "WARNING: Kong did not respond within 180s. Check: docker compose -f $BACKEND_DIR/docker-compose.yml ps"
