UPDATE public.api_providers
SET response_data_mapping = '{
  "udyam_number": "data.uan",
  "enterprise_name": "data.main_details.name_of_enterprise",
  "enterprise_type": "data.main_details.enterprise_type_list.0.enterprise_type",
  "major_activity": "data.main_details.major_activity",
  "social_category": "data.main_details.social_category",
  "organization_type": "data.main_details.organization_type",
  "registration_date": "data.main_details.registration_date",
  "date_of_incorporation": "data.main_details.date_of_incorporation",
  "date_of_commencement": "data.main_details.date_of_commencement",
  "applied_date": "data.main_details.applied_date",
  "state": "data.main_details.state",
  "district": "data.main_details.dic_name",
  "city": "data.main_details.city",
  "village": "data.main_details.village",
  "road": "data.main_details.road",
  "flat": "data.main_details.flat",
  "pin_code": "data.main_details.pin",
  "mobile": "data.main_details.mobile_number",
  "email": "data.main_details.email",
  "msme_dfo": "data.main_details.msme_dfo",
  "gender": "data.main_details.gender",
  "nic_2_digit": "data.nic_code.0.nic_2_digit",
  "nic_4_digit": "data.nic_code.0.nic_4_digit",
  "nic_5_digit": "data.nic_code.0.nic_5_digit",
  "plant_locations": "data.location_of_plant_details"
}'::jsonb,
    updated_at = now()
WHERE provider_name = 'MSME';